[package]
name = "rtd"
version = "0.1.0"
authors = ["yutaodou@gmail.com"]
edition = "2018"

[dependencies]
rusqlite = "0.21.0"
time = "0.2.9"
ansi_term = "0.12"
clap = "2.33.0"
dirs = "2.0.2"
anyhow = "1.0"